### ISSUE TITLE
Add others signs

### ISSUE THREAD

**Issue by Snufflay** [hallopiu/PowerSigns#3]
Hi, only oak_sign working with paysign! Another signs like spruce, birch, jungle, acacia and dark oak not working!

**Comment by redslime** [comment]
Added in https://github.com/hallopiu/PowerSigns/commit/7d317217f7bf4e5ea2042f4a0faeba38a1d061ea. Download the latest version on the [spigot page](https://www.spigotmc.org/resources/powersigns.51501/)
