### ISSUE TITLE
Block destorying redstone block

### ISSUE THREAD

**Issue by Snufflay** [hallopiu/PowerSigns#4]
Hi, I have problem with players. I mean when someone click and paid, sign changed to redstone block then another player can destroy that redstone block. Any way to block it?

**Comment by redslime** [comment]
Fixed in https://github.com/hallopiu/PowerSigns/commit/b2e2acadcedb57e02f5d7014d11d0d9bce3c8fc0. Download the latest version on the [spigot page](https://www.spigotmc.org/resources/powersigns.51501/)
